//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Migration
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicineMaster
    {
        public int Id { get; set; }
        public string MedicineName { get; set; }
        public Nullable<long> MedicineType { get; set; }
        public Nullable<int> MedicineTypeNavigationId { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual TblMedicineType TblMedicineType { get; set; }
    }
}
