//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Migration
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AASTHAEntities : DbContext
    {
        public AASTHAEntities()
            : base("name=AASTHAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_appointment> tbl_appointment { get; set; }
        public virtual DbSet<tbl_shift> tbl_shift { get; set; }
        public virtual DbSet<C__EFMigrationsHistory> C__EFMigrationsHistory { get; set; }
        public virtual DbSet<delivery_master> delivery_master { get; set; }
        public virtual DbSet<DeliveryMaster> DeliveryMasters { get; set; }
        public virtual DbSet<diagnosis_master> diagnosis_master { get; set; }
        public virtual DbSet<DiagnosisMaster> DiagnosisMasters { get; set; }
        public virtual DbSet<general_diagnosis> general_diagnosis { get; set; }
        public virtual DbSet<GeneralDiagnosi> GeneralDiagnosis { get; set; }
        public virtual DbSet<IPD_Charge_Details> IPD_Charge_Details { get; set; }
        public virtual DbSet<IPD_Charges_Master> IPD_Charges_Master { get; set; }
        public virtual DbSet<IpdChargeDetail> IpdChargeDetails { get; set; }
        public virtual DbSet<IpdChargesMaster> IpdChargesMasters { get; set; }
        public virtual DbSet<medicine_master> medicine_master { get; set; }
        public virtual DbSet<MedicineMaster> MedicineMasters { get; set; }
        public virtual DbSet<operation_master> operation_master { get; set; }
        public virtual DbSet<OperationMaster> OperationMasters { get; set; }
        public virtual DbSet<tbl_delivery> tbl_delivery { get; set; }
        public virtual DbSet<tbl_general> tbl_general { get; set; }
        public virtual DbSet<tbl_Ipd> tbl_Ipd { get; set; }
        public virtual DbSet<tbl_medicine_type> tbl_medicine_type { get; set; }
        public virtual DbSet<tbl_opd> tbl_opd { get; set; }
        public virtual DbSet<tbl_operation> tbl_operation { get; set; }
        public virtual DbSet<tbl_patient> tbl_patient { get; set; }
        public virtual DbSet<tbl_user> tbl_user { get; set; }
        public virtual DbSet<TblIpd> TblIpds { get; set; }
        public virtual DbSet<TblMedicineType> TblMedicineTypes { get; set; }
        public virtual DbSet<TblPatient> TblPatients { get; set; }
    }
}
