//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Migration
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblIpd
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblIpd()
        {
            this.IpdChargeDetails = new HashSet<IpdChargeDetail>();
        }
    
        public int Id { get; set; }
        public string IpdReceiptId { get; set; }
        public string DeptName { get; set; }
        public Nullable<long> PatientId { get; set; }
        public string RoomType { get; set; }
        public Nullable<System.DateTime> AddmissionDate { get; set; }
        public Nullable<System.DateTime> DischargeDate { get; set; }
        public Nullable<decimal> Bill { get; set; }
        public Nullable<decimal> Conssesion { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public Nullable<int> PatientId1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IpdChargeDetail> IpdChargeDetails { get; set; }
        public virtual TblPatient TblPatient { get; set; }
    }
}
